version: '3.1'
services:
  db:
    image: postgres:11.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: tree
    volumes:
      - ./postgresql:/var/lib/postgresql/data
